<?php

declare(strict_types=1);

namespace Native\Symfony\Mobile\Tests;

use Native\Symfony\Mobile\Ui\Style\ArrayThemeColorResolver;
use Native\Symfony\Mobile\Ui\Style\StyleParser;
use PHPUnit\Framework\TestCase;

/**
 * Pins {@see StyleParser} to upstream's `TailwindParser` output.
 *
 * `tests/fixtures/tailwind-corpus.json` was generated by running upstream's parser over its
 * own kitchen-sink demo: 684 distinct tokens and 1,336 distinct class strings, each with the
 * exact array upstream returned. That fixture — not this file's opinion of what Tailwind
 * means — is the oracle, because the far side of the wire is upstream's Kotlin and Swift.
 * Regenerating it against a new upstream tag turns drift into a diff.
 *
 * Two things the fixture cannot express, both handled explicitly below:
 *
 *  - **Numeric type.** It is JSON, so `24.0` came back as `24` and the explicit-inset
 *    `-0.0` as `-0`. Comparison therefore runs through {@see normalise()}, which folds
 *    integral floats to ints — and the sign of an explicit zero gets its own test.
 *  - **Our one deliberate divergence.** Upstream's theme-border branch clobbers a preceding
 *    explicit `border-<n>`; we do not. The four affected class strings are listed in
 *    {@see UPSTREAM_BORDER_WIDTH_BUG} and patched before comparison.
 *
 * Key order is compared, not just contents: element content hashes are computed over the
 * emitted arrays, so a reordering would change a hash and defeat subtree reuse.
 */
final class UiStyleParserTest extends TestCase
{
    /**
     * Class strings where upstream's `border-theme-*` branch overwrites an explicit border
     * width with 1. We keep the author's width; the value here is what our parser emits.
     *
     * All four occur in upstream's own demo, which is therefore rendering 1pt borders where
     * it asks for 2pt and 4pt. See StyleParser::THEME_BORDER_WIDTH.
     *
     * @var array<string, int>
     */
    private const UPSTREAM_BORDER_WIDTH_BUG = [
        'border-2 border-theme-primary rounded-lg px-5 py-2 items-center justify-center' => 2,
        'flex-1 items-center gap-2 rounded-xl border-2 border-theme-outline bg-theme-surface p-4' => 2,
        'flex-1 items-center gap-2 rounded-xl border-2 border-theme-outline-variant bg-theme-surface p-4' => 2,
        'w-[36] h-[36] rounded-full bg-[#00677d] items-center justify-center border-4 border-theme-background' => 4,
    ];

    /** @var array<string, mixed>|null */
    private static ?array $corpus = null;

    // ---------------------------------------------------------------- corpus

    public function testEveryCorpusTokenMatchesUpstream(): void
    {
        $parser = $this->parser();
        $tokens = self::corpus()['tokens'];
        $mismatches = [];

        foreach ($tokens as $token => $expected) {
            $actual = $this->normalise($parser->parse((string) $token));

            if ($actual !== $this->normalise($expected)) {
                $mismatches[(string) $token] = $actual;
            }
        }

        self::assertSame([], $mismatches, sprintf(
            '%d of %d corpus tokens diverge from upstream.',
            \count($mismatches),
            \count($tokens),
        ));
    }

    /**
     * The compositionality claim: parsing a whole string equals parsing its tokens and
     * merging them with the dark/gradient deep-merge rule. This is the assertion that would
     * fail first if {@see StyleParser::parse()} lost the merge rule — measured at 27
     * divergences with a flat merge.
     */
    public function testEveryCorpusClassStringMatchesUpstream(): void
    {
        $parser = $this->parser();
        $strings = self::corpus()['classStrings'];
        $mismatches = [];

        foreach ($strings as $classString => $expected) {
            $classString = (string) $classString;
            $expected = $this->normalise($expected);

            if (isset(self::UPSTREAM_BORDER_WIDTH_BUG[$classString])) {
                $expected['borderWidth'] = self::UPSTREAM_BORDER_WIDTH_BUG[$classString];
            }

            $actual = $this->normalise($parser->parse($classString));

            if ($actual !== $expected) {
                $mismatches[$classString] = $actual;
            }
        }

        self::assertSame([], $mismatches, sprintf(
            '%d of %d corpus class strings diverge from upstream.',
            \count($mismatches),
            \count($strings),
        ));
    }

    /**
     * Theme tokens are an application hook, not vocabulary: with no resolver they resolve to
     * nothing at all rather than to some built-in default. 31 of the 684 corpus tokens.
     */
    public function testThemeTokensResolveToNothingWithoutAResolver(): void
    {
        $parser = new StyleParser();

        foreach (self::corpus()['themeTokensWithoutResolver'] as $token => $expected) {
            self::assertSame([], $expected, 'fixture sanity');
            self::assertSame([], $parser->parse((string) $token), $token.' should need a resolver');
        }
    }

    /**
     * Malformed fragments left behind by stripping Blade interpolation out of the corpus.
     * They are extraction noise rather than real classes, and the point is that they parse
     * to nothing instead of throwing — a template with a runtime-built class string must not
     * be able to 500 a screen.
     */
    public function testMalformedFragmentsParseToNothing(): void
    {
        $parser = $this->parser();

        foreach (array_keys(self::corpus()['extractionArtifacts']) as $fragment) {
            self::assertSame([], $parser->parse((string) $fragment), $fragment.' should parse to nothing');
        }
    }

    // ------------------------------------------------------------ merge rule

    /**
     * THE merge rule, directly. Two theme classes each contribute one `dark` key; a flat
     * array_merge keeps only the second.
     */
    public function testDarkCompanionsFromSeveralClassesAreDeepMerged(): void
    {
        $result = $this->parser()->parse('bg-theme-surface border-theme-outline text-theme-on-surface');

        self::assertSame([
            'bg' => '#92A2B2',
            'borderColor' => '#8C9CAC',
            'color' => '#8A9AAA',
        ], $result['dark']);
    }

    /** `dark:` composes with any rule, so the same accumulation happens for explicit variants. */
    public function testExplicitDarkVariantsFromSeveralClassesAreDeepMerged(): void
    {
        $result = $this->parser()->parse('dark:bg-gray-800 dark:text-[#B0B3B8] dark:border-slate-800');

        self::assertSame([
            'dark' => [
                'bg' => '#1F2937',
                'color' => '#B0B3B8',
                'borderColor' => '#1E293B',
            ],
        ], $result);
    }

    /**
     * Gradients are the second nested-merge case, and the corpus does not exercise them at
     * all — direction and every stop arrive as separate classes contributing separate keys
     * to one `gradient` array.
     */
    public function testGradientDirectionAndStopsAreDeepMerged(): void
    {
        $result = $this->parser()->parse('bg-linear-to-br from-black via-black/10 to-transparent');

        self::assertSame([
            'gradient' => [
                'direction' => [1.0, 1.0],
                'from' => '#000000',
                'via' => '#1A000000',
                'to' => '#00000000',
            ],
        ], $result);
    }

    /** The v3 spelling of the same thing, and a themed stop. */
    public function testGradientAcceptsV3SpellingAndThemedStops(): void
    {
        self::assertSame(
            ['gradient' => ['direction' => [0.0, -1.0], 'from' => '#1E2E3E']],
            $this->parser()->parse('bg-gradient-to-t from-theme-primary'),
        );
    }

    // ------------------------------------------------- deliberate divergence

    /**
     * DIVERGES FROM UPSTREAM DELIBERATELY.
     *
     * Upstream emits `borderWidth: 1` here, because its theme-border branch sets the width
     * unconditionally and the class follows `border-2`. We treat the theme width as a
     * default, so the author's 2 survives — and a bare theme border still gets its 1, since
     * a border colour with no width paints nothing.
     */
    public function testThemeBorderDoesNotClobberAnExplicitWidth(): void
    {
        $parser = $this->parser();

        self::assertSame(2, $parser->parse('border-2 border-theme-outline')['borderWidth']);
        // Upstream is already correct in this order; both orders now agree.
        self::assertSame(2, $parser->parse('border-theme-outline border-2')['borderWidth']);
        self::assertSame(1, $parser->parse('border-theme-outline')['borderWidth']);
        // The fix must not leak into the colour keys.
        self::assertSame('#1C2C3C', $parser->parse('border-2 border-theme-outline')['borderColor']);
        self::assertSame(['borderColor' => '#8C9CAC'], $parser->parse('border-2 border-theme-outline')['dark']);
    }

    /**
     * The implied width is carried through the merge under an internal marker key, so the
     * dark companion needs the same treatment — a themed border can be authored inside a
     * `dark:` variant, and a leaked marker would reach the wire.
     *
     * The first assertion matches upstream exactly (including the theme token's own
     * companion nesting one level deeper); the second is our fix, applied consistently
     * inside the dark scope.
     */
    public function testTheImpliedBorderWidthIsResolvedInsideTheDarkCompanionToo(): void
    {
        $parser = $this->parser();

        self::assertSame([
            'dark' => [
                'borderColor' => '#1C2C3C',
                'borderWidth' => 1,
                'dark' => ['borderColor' => '#8C9CAC'],
            ],
        ], $parser->parse('dark:border-theme-outline'));

        self::assertSame(2, $parser->parse('dark:border-2 dark:border-theme-outline')['dark']['borderWidth']);
    }

    /** A non-theme border colour never carried an implied width, and still does not. */
    public function testPaletteBorderColourCarriesNoImpliedWidth(): void
    {
        self::assertSame(['borderColor' => '#334155'], $this->parser()->parse('border-slate-700'));
        self::assertSame(
            ['borderWidth' => 2, 'borderColor' => '#334155'],
            $this->parser()->parse('border-2 border-slate-700'),
        );
        self::assertSame(
            ['dark' => ['borderColor' => '#1E293B']],
            $this->parser()->parse('dark:border-slate-800'),
        );
    }

    // ----------------------------------------------- reproduced upstream quirks

    /**
     * `w-[50%]` drops the percent and becomes points, while `w-1/2` is a percent string.
     * Two spellings of one intent, two results — reproduced, because the renderers read a
     * bare number as points and the fraction table is what feeds them percents.
     */
    public function testArbitraryPercentWidthLosesItsUnit(): void
    {
        self::assertSame(['width' => 50], $this->normalise($this->parser()->parse('w-[50%]')));
        self::assertSame(['width' => '50%'], $this->parser()->parse('w-1/2'));
    }

    /** Fraction widths are pre-rounded to whole percents in the table: `2/3` is 67%, not 66.667%. */
    public function testWidthFractionsArePreRounded(): void
    {
        self::assertSame(['width' => '67%'], $this->parser()->parse('w-2/3'));
        self::assertSame(['width' => '17%'], $this->parser()->parse('w-1/6'));
    }

    /** Opacity is not clamped; the renderers clamp on their side. */
    public function testOpacityIsUnclamped(): void
    {
        self::assertSame(['opacity' => 2.0], $this->parser()->parse('opacity-200'));
        self::assertSame(['opacity' => 0.5], $this->parser()->parse('opacity-50'));
    }

    /**
     * The spacing scale is a whitelist: 52 is derivable from `p-13` and is deliberately not
     * derived, because Tailwind generates no such class. The token lands in diagnostics.
     */
    public function testSpacingScaleIsAWhitelistNotArithmetic(): void
    {
        $dropped = [];

        self::assertSame([], $this->parser()->parse('p-13', $dropped));
        self::assertSame(['p-13'], $dropped);
        // The same value, asked for explicitly, is accepted.
        self::assertSame(['padding' => 52], $this->normalise($this->parser()->parse('p-[52]')));
        // And 52 *is* in the scale for the utilities Tailwind does generate.
        self::assertSame(['padding' => 208], $this->parser()->parse('p-52'));
    }

    /**
     * Hex byte order: CSS in, ARGB out. 8-digit input moves its alpha to the front, 4-digit
     * does the same after expanding, 3-digit just expands, and a `/N` modifier overwrites
     * whatever alpha the value carried.
     */
    public function testArbitraryHexIsNormalisedToWireByteOrder(): void
    {
        $parser = $this->parser();

        self::assertSame(['bg' => '#78123456'], $parser->parse('bg-[#12345678]'));
        self::assertSame(['bg' => '#80123456'], $parser->parse('bg-[#12345678]/50'));
        self::assertSame(['color' => '#AABBCC'], $parser->parse('text-[#ABC]'));
        self::assertSame(['bg' => '#DDAABBCC'], $parser->parse('bg-[#ABCD]'));
        self::assertSame(['bg' => '#66000000'], $parser->parse('bg-[#00000066]'));
        // Not hex at all: dropped rather than shipped raw, which would render black.
        self::assertSame([], $parser->parse('bg-[#12345]'));
    }

    /** `/N` alpha applies to palette, named and theme colours alike, light and dark. */
    public function testAlphaModifierAppliesToEveryColourRule(): void
    {
        $parser = $this->parser();

        self::assertSame(['bg' => '#4DFCA5A5'], $parser->parse('bg-red-300/30'));
        self::assertSame(['bg' => '#80000000'], $parser->parse('bg-black/50'));
        self::assertSame(
            ['dark' => ['bg' => '#268B9BAB'], 'bg' => '#261B2B3B'],
            $parser->parse('bg-theme-on-surface-variant/15'),
        );
        // Bracketed alpha, the Tailwind v3+ arbitrary spelling.
        self::assertSame(['bg' => '#45EF4444'], $parser->parse('bg-red-500/[27]'));
    }

    /**
     * A uniform radius and a per-corner one coexist rather than merging, so the result does
     * not depend on which order the author wrote them in.
     */
    public function testUniformAndPerCornerRadiiAreBothEmitted(): void
    {
        self::assertSame([
            'borderRadius' => 16,
            'borderRadiusTopLeft' => 16,
            'borderRadiusTopRight' => 16,
        ], $this->parser()->parse('rounded-2xl rounded-t-2xl'));

        // A bare side takes the same 4pt default a bare `rounded` does.
        self::assertSame(
            ['borderRadiusBottomRight' => 4, 'borderRadiusBottomLeft' => 4],
            $this->parser()->parse('rounded-b'),
        );
    }

    /** The glass bitmask: enabled 1, prominent 2, interactive 4, clear 8, in any order. */
    public function testGlassModifiersPackIntoABitmask(): void
    {
        $parser = $this->parser();

        self::assertSame(['glass' => 1], $parser->parse('glass'));
        self::assertSame(['glass' => 3], $parser->parse('glass:prominent'));
        self::assertSame(['glass' => 9], $parser->parse('glass:clear'));
        self::assertSame(['glass' => 13], $parser->parse('glass:clear:interactive'));
        self::assertSame(['glass' => 13], $parser->parse('glass:interactive:clear'));
        // A typo costs the modifier, not the effect.
        self::assertSame(['glass' => 1], $parser->parse('glass:thicc'));
    }

    /**
     * An explicitly authored zero inset must be distinguishable from an unset one, and the
     * packed node has no spare byte for the distinction — so the sign bit carries it. The
     * JSON fixture flattens `-0.0` to `-0`, hence the dedicated test.
     */
    public function testExplicitZeroInsetsKeepTheirSignBit(): void
    {
        $result = $this->parser()->parse('bottom-0 left-0');

        self::assertSame([-0.0, -0.0], array_values($result));
        foreach ($result as $key => $value) {
            // fdiv rather than a comparison: -0.0 == 0.0, so the sign bit is only visible
            // through an operation that keeps it.
            self::assertTrue(\is_float($value) && -\INF === fdiv(1, $value), $key.' should be -0.0');
        }

        // A non-zero inset is untouched, and a non-inset zero stays a plain int.
        self::assertSame(['positionTop' => 8], $this->parser()->parse('top-2'));
        self::assertSame(['padding' => 0], $this->parser()->parse('p-0'));
    }

    /** Tokens upstream itself drops. Reproducing the drop is the fidelity requirement. */
    public function testTokensUpstreamDropsAreDropped(): void
    {
        $parser = $this->parser();
        $dropped = [];

        // `border-t` and friends: the node carries one width for all four edges, so there is
        // no directional border width at all. A real gap against Tailwind, kept visible.
        // `text-7xl`: the size scale stops at 6xl. `mx-auto`: `auto` is not a spacing value.
        // `font-black`: a real weight with no renderer ordinal.
        $classes = 'border-t border-x-2 text-7xl mx-auto overflow-hidden origin-bottom-right anchor-top-left font-black font-extralight';

        self::assertSame([], $parser->parse($classes, $dropped));
        self::assertSame(explode(' ', $classes), $dropped);
    }

    // --------------------------------------------------------- variants, platform

    /**
     * The fixture was generated with no platform, so its `ios:`/`android:` entries are all
     * empty. These four resolve once a platform is set — the analysis records the expected
     * values, which is the only place they are pinned.
     */
    public function testPlatformVariantsResolveOnTheMatchingPlatform(): void
    {
        $android = $this->parser()->withPlatform('android');
        $ios = $this->parser()->withPlatform('ios');

        self::assertSame(['bg' => '#4DEF4444'], $android->parse('android:bg-red-500/30'));
        self::assertSame([], $ios->parse('android:bg-red-500/30'));
        self::assertSame(['bg' => '#4D67E8F9'], $ios->parse('ios:bg-cyan-300/30'));

        // Variants compose in either nesting order.
        self::assertSame(['dark' => ['bg' => '#FFFFFF']], $android->parse('android:dark:bg-white'));
        self::assertSame(['dark' => ['bg' => '#FFFFFF']], $android->parse('dark:android:bg-white'));
        // A theme token under `dark:` nests one level deeper: the variant wraps the whole
        // theme result, which already carries its own dark companion. Upstream does exactly
        // the same — the analysis's claim that this token "resolves correctly" once a
        // platform is set overstates it, since the collector only reads one level of `dark`.
        // Reproduced rather than fixed: the shape is upstream's and the renderers see it.
        self::assertSame(
            ['dark' => ['bg' => '#233343', 'dark' => ['bg' => '#93A3B3']]],
            $android->parse('android:dark:bg-theme-surface-variant'),
        );
    }

    /**
     * A variant aimed at the other platform is an intentional no-op, so it must not be
     * reported as a dropped class — otherwise every cross-platform template logs warnings
     * about classes that are working as intended.
     */
    public function testInactivePlatformVariantsAreNotReportedAsDropped(): void
    {
        $dropped = [];

        $this->parser()->withPlatform('ios')->parse('android:bg-red-500 p-13 bg-nonsense-500', $dropped);

        self::assertSame(['p-13', 'bg-nonsense-500'], $dropped);
    }

    /** Negatives: only margins and insets may go negative; anything else is treated as a typo. */
    public function testOnlyMarginsAndInsetsMayGoNegative(): void
    {
        $parser = $this->parser();

        self::assertSame(['marginTop' => -16.0], $parser->parse('-mt-4'));
        self::assertSame(['positionRight' => -32.0], $parser->parse('-right-8'));
        self::assertSame(['marginLeft' => -6], $this->normalise($parser->parse('ml-[-6]')));
        self::assertSame([], $parser->parse('-p-4'));
        self::assertSame([], $parser->parse('-w-4'));
        // Composes with the variant prefixes, which is why the sign is stripped after them.
        self::assertSame(['positionRight' => -32.0], $parser->withPlatform('ios')->parse('ios:-right-8'));
        self::assertSame([], $parser->parse('ios:-right-8'));
    }

    // ------------------------------------------------------------ theme hook

    /** A theme with no dark set, or with identical hexes, emits no dark companion. */
    public function testIdenticalLightAndDarkThemeHexesEmitNoDarkCompanion(): void
    {
        $sameBoth = new StyleParser(new ArrayThemeColorResolver(['primary' => '#ABCDEF'], ['primary' => '#ABCDEF']));
        self::assertSame(['bg' => '#ABCDEF'], $sameBoth->parse('bg-theme-primary'));

        $lightOnly = new StyleParser(new ArrayThemeColorResolver(['primary' => '#ABCDEF']));
        self::assertSame(['color' => '#ABCDEF'], $lightOnly->parse('text-theme-primary'));
    }

    /** An unknown theme token drops and is reported — that is how a theme typo gets found. */
    public function testUnknownThemeTokenIsReported(): void
    {
        $dropped = [];

        self::assertSame([], $this->parser()->parse('bg-theme-nonexistent', $dropped));
        self::assertSame(['bg-theme-nonexistent'], $dropped);
    }

    /** The service is immutable; `with*` returns a new instance rather than mutating shared state. */
    public function testWithersDoNotMutateTheOriginalInstance(): void
    {
        $base = new StyleParser();
        $themed = $base->withThemeColors(new ArrayThemeColorResolver(['primary' => '#ABCDEF']));

        self::assertSame([], $base->parse('bg-theme-primary'));
        self::assertSame(['bg' => '#ABCDEF'], $themed->parse('bg-theme-primary'));
        self::assertNotSame($base, $themed);
    }

    // ------------------------------------------------------------------ misc

    /** The examples in NATIVE-UI-CONTRACT.md §4d, so the document stays honest. */
    public function testContractExamples(): void
    {
        $parser = $this->parser();

        self::assertSame(['flexGrow' => 1, 'flexShrink' => 1, 'flexBasis' => 0], $parser->parse('flex-1'));
        self::assertSame(['padding' => 16], $parser->parse('p-4'));
        self::assertSame(
            ['paddingLeft' => 8, 'paddingRight' => 8, 'paddingTop' => 12, 'paddingBottom' => 12],
            $parser->parse('px-2 py-3'),
        );
        self::assertSame(['gap' => 8], $parser->parse('gap-2'));
        self::assertSame(['bg' => '#0F172A'], $parser->parse('bg-slate-900'));
        self::assertSame(['color' => '#FFFFFF'], $parser->parse('text-white'));
        self::assertSame(['fontSize' => 24, 'fontWeight' => 6], $parser->parse('text-2xl font-bold'));
        self::assertSame(['borderRadius' => 8], $parser->parse('rounded-lg'));
        self::assertSame(['alignItems' => 1, 'justifyContent' => 3], $parser->parse('items-center justify-between'));
        self::assertSame(['fillWidth' => true, 'height' => 48], $parser->parse('w-full h-12'));
        self::assertSame(['opacity' => 0.5], $parser->parse('opacity-50'));
        self::assertSame(['elevation' => 6], $parser->parse('shadow-md'));
        self::assertSame(['borderWidth' => 1, 'borderColor' => '#334155'], $parser->parse('border border-slate-700'));
        self::assertSame(
            ['flexGrow' => 1, 'flexShrink' => 1, 'flexBasis' => 0, 'paddingLeft' => 12, 'paddingRight' => 12, 'bg' => '#0F172A', 'fontSize' => 24],
            $parser->parse('flex-1 px-3 bg-slate-900 text-2xl'),
        );
    }

    /** Alignment 0 means UNSET, so start is 4 — the byte a renderer default would otherwise claim. */
    public function testAlignmentStartIsFourBecauseZeroMeansUnset(): void
    {
        $parser = $this->parser();

        self::assertSame(['alignItems' => 4], $parser->parse('items-start'));
        self::assertSame(['alignSelf' => 4], $parser->parse('self-start'));
        self::assertSame(['alignSelf' => 3], $parser->parse('self-stretch'));
        // justify-content has no unset problem, so its start really is 0.
        self::assertSame(['justifyContent' => 0], $parser->parse('justify-start'));
        // Tailwind's vocabulary only — our friendlier aliases are not classes.
        self::assertSame([], $parser->parse('items-fill justify-spacebetween'));
    }

    /** Branches the corpus never exercises. Untested code here is silently-wrong code. */
    public function testBranchesTheCorpusDoesNotExercise(): void
    {
        $parser = $this->parser();

        self::assertSame(['fit' => 2], $parser->parse('object-cover'));
        self::assertSame(['aspectRatio' => 1.0], $parser->parse('aspect-square'));
        self::assertSame(['aspectRatio' => 16 / 9], $parser->parse('aspect-video'));
        self::assertSame(['aspectRatio' => 16 / 9], $parser->parse('aspect-[16/9]'));
        self::assertSame(['aspectRatio' => 0.0], $parser->parse('aspect-[16/0]'));
        self::assertSame(['selectable' => 1], $parser->parse('select-text'));
        self::assertSame(['positionTop' => -0.0, 'positionRight' => -0.0, 'positionBottom' => -0.0, 'positionLeft' => -0.0], $parser->parse('inset-0'));
        self::assertSame(['positionLeft' => 8, 'positionRight' => 8], $parser->parse('inset-x-2'));
        self::assertSame(['safeAreaTop' => true], $parser->parse('safe-area-top'));
        self::assertSame(['minHeight' => 96], $parser->parse('min-h-24'));
        self::assertSame(['maxWidth' => 896], $parser->parse('max-w-4xl'));
        self::assertSame(['maxWidth' => 0], $parser->parse('max-w-none'));
        // The container scale is width-only, mirroring Tailwind.
        self::assertSame([], $parser->parse('max-h-4xl'));
        self::assertSame(['flexDirection' => 1], $parser->parse('flex-row'));
        self::assertSame(['flexWrap' => 0], $parser->parse('flex-nowrap'));
        self::assertSame(['flexGrow' => 1], $parser->parse('grow'));
        self::assertSame(['underline' => 0, 'lineThrough' => 0], $parser->parse('no-underline'));
        self::assertSame(['fontStyle' => 0], $parser->parse('not-italic'));
        self::assertSame(['borderWidth' => 0], $parser->parse('border-0'));
        self::assertSame(['borderWidth' => 8], $parser->parse('border-8'));
        self::assertSame(['bg' => '#020617'], $parser->parse('bg-slate-950'));
        self::assertSame(['bg' => '#00000000'], $parser->parse('bg-transparent'));
        self::assertSame(['lineHeightPx' => 24.0], $parser->parse('leading-[24px]'));
        self::assertSame(['lineHeight' => 1.4], $parser->parse('leading-[1.4]'));
        self::assertSame(['borderRadiusBottomRight' => 4.0], $parser->parse('rounded-br-[4]'));
        self::assertSame(['borderRadius' => 0], $parser->parse('rounded-none'));
        // Logical (writing-direction) radius spellings stay unparsed: neither renderer flips
        // corners for RTL, so accepting them would render LTR geometry in an RTL layout.
        self::assertSame([], $parser->parse('rounded-s-lg'));
    }

    /** Whitespace handling: an attribute is whatever the template emitted, newlines included. */
    public function testWhitespaceAndEmptyInput(): void
    {
        $parser = $this->parser();

        self::assertSame([], $parser->parse(''));
        self::assertSame([], $parser->parse("   \n  "));
        self::assertSame(['padding' => 16, 'gap' => 8], $parser->parse("  p-4 \n\t gap-2  "));
    }

    /** Later classes win on the same key, as in a stylesheet. */
    public function testLaterClassesWinOnTheSameKey(): void
    {
        self::assertSame(['padding' => 32], $this->parser()->parse('p-4 p-8'));
        self::assertSame(['bg' => '#000000'], $this->parser()->parse('bg-white bg-black'));
    }

    // ------------------------------------------------------------- helpers

    /** A parser wired with the fixture's sentinel theme tables, exactly as it was generated. */
    private function parser(): StyleParser
    {
        $meta = self::corpus()['_meta'];

        return new StyleParser(new ArrayThemeColorResolver($meta['themeResolverLight'], $meta['themeResolverDark']));
    }

    /** @return array<string, mixed> */
    private static function corpus(): array
    {
        if (null === self::$corpus) {
            $json = file_get_contents(__DIR__.'/fixtures/tailwind-corpus.json');
            self::assertIsString($json, 'corpus fixture is unreadable');
            self::$corpus = json_decode($json, true, 512, \JSON_THROW_ON_ERROR);
        }

        return self::$corpus;
    }

    /**
     * Fold integral floats to ints, recursively.
     *
     * Only for comparison against the fixture, which is JSON: PHP's `json_encode` drops the
     * zero fraction, so upstream's `24.0` was recorded as `24` and `-0.0` as `-0`. Without
     * this, every arbitrary-value token would look like a mismatch on type alone. The
     * distinctions that matter and are lost here — the sign of an explicit zero, and int vs
     * float for the same number — are asserted separately and directly.
     *
     * @param mixed $value
     *
     * @return mixed
     */
    private function normalise(mixed $value): mixed
    {
        if (\is_array($value)) {
            return array_map([$this, 'normalise'], $value);
        }

        if (\is_float($value) && $value === floor($value) && \abs($value) < \PHP_INT_MAX) {
            return (int) $value;
        }

        return $value;
    }
}
